apiVersion: v1
kind: Template
labels:
  app: '${PROJECT}-${COMPONENT}'
parameters:
  - name: PROJECT
    displayName: Application
    description: The name of the application project.
    required: true
  - name: COMPONENT
    displayName: Component
    description: The name of the application component.
    required: true
  - name: ENV
    displayName: Environment
    description: The environment stage.
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory available for the container.
    value: 256Mi
  - name: MEMORY_REQUEST
    displayName: Memory Request
    description: Minimum amount of memory requested for the container.
    value: 128Mi
  - name: CPU_LIMIT
    displayName: CPU Limit
    description: Maximum CPU (milli) cores available for the container.
    value: 100m
  - name: CPU_REQUEST
    displayName: CPU Request
    description: Minimum CPU (milli) cores requested for the container.
    value: 50m
  - name: TAGVERSION
    displayName: tag version
    description: The version to be used.
    value: latest
    required: true
  - name: COMPLETION_DEADLINE_SECONDS
    displayName: Completion Deadline Seconds
    description: how long the docker build of the component can last before it is canceled
    value: "1800"
  - name: OPENSHIFT_HOST
    displayName: OPENSHIFT_HOST
    description: Host of the openshift exposed public addresses.
    value: "ocp.odsbox.lan"
  - name: APP_NAME
    displayName: APP_NAME
    description: Default front-end app name.
    value: "demo-app-front-end"
  - name: SERVICE
    displayName: SERVICE
    description: Default sevice and port of the front-end.
    value: "demo-app-front-end:8080"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: '${COMPONENT}'
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: '${COMPONENT}'
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${COMPONENT}
    spec:
      completionDeadlineSeconds: "${{COMPLETION_DEADLINE_SECONDS}}"
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${COMPONENT}:${TAGVERSION}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        type: Binary
        binary: {}
      strategy:
        type: Docker
        dockerStrategy: {}
      successfulBuildsHistoryLimit: 5
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: '${COMPONENT}'
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: '${PROJECT}-${COMPONENT}'
        deploymentconfig: '${COMPONENT}'
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: '${PROJECT}-${COMPONENT}'
            deploymentconfig: '${COMPONENT}'
            env: '${ENV}'
        spec:
          containers:   
            - env:
              - name: OPENSHIFT_HOST
                value: '${OPENSHIFT_HOST}'
              - name: OPENSHIFT_BUILD_NAMESPACE
                value: '${PROJECT}-${ENV}'
              - name: APP_NAME
                value: '${APP_NAME}'
              - name: OPENSHIFT_APP_SERVICE
                value: '${SERVICE}'
              - name: USER_TEST_LOGIN
                value: 'user'
              - name: USER_TEST_PASSWORD
                value: 'password'
              image: '${PROJECT}-${ENV}/${COMPONENT}:${TAGVERSION}'
              imagePullPolicy: IfNotPresent
              name: '${COMPONENT}'
              resources:
                limits:
                  cpu:  '${CPU_LIMIT}'
                  memory: '${MEMORY_LIMIT}'
                requests:
                  cpu:  '${CPU_REQUEST}'
                  memory: '${MEMORY_REQUEST}'
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File                             
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - '${COMPONENT}'
            from:
              kind: ImageStreamTag
              name: '${COMPONENT}:${TAGVERSION}'
              namespace: '${PROJECT}-${ENV}'
          type: ImageChange
         
